//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alytalo_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVC_Alytalo_dbEntities : DbContext
    {
        public MVC_Alytalo_dbEntities()
            : base("name=MVC_Alytalo_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Huoneet> Huoneet { get; set; }
        public virtual DbSet<Kiukaat> Kiukaat { get; set; }
        public virtual DbSet<Lampotilat> Lampotilat { get; set; }
        public virtual DbSet<Valot> Valot { get; set; }
    }
}
