//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alytalo_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lampotilat
    {
        public int Lampotila_id { get; set; }
        public int Huone { get; set; }
        public Nullable<int> NykyLampotila { get; set; }
        public Nullable<int> TavoiteLampotila { get; set; }
    
        public virtual Huoneet Huoneet { get; set; }
    }
}
