//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alytalo_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valot
    {
        public int Valo_id { get; set; }
        public int Huone { get; set; }
        public string Valaisin { get; set; }
        public string ValonTila { get; set; }
        public string ValonMaara { get; set; }
    
        public virtual Huoneet Huoneet { get; set; }
    }
}
